<?php

namespace App\Http\Resources\Material;

use Illuminate\Http\Request;
use Illuminate\Http\Resources\Json\JsonResource;

class MaterialResource extends JsonResource
{
    public function toArray(Request $request): array
    {
        return [
            'id' => $this->id,
            'material_code' => $this->material_code,
            'material_name' => $this->material_name,
            'material_description' => $this->material_description,
            'material_category' => $this->material_category,
            'material_sub_category' => $this->material_sub_category,
            'material_type' => $this->material_type,
            'brand' => $this->brand,
            'manufacturer' => $this->manufacturer,
            'material_status' => $this->material_status,
            'uom' => $this->uom,
            'alternate_uom' => $this->alternate_uom,
            'conversion_factor' => $this->conversion_factor,
            'weight' => $this->weight,
            'length' => $this->length,
            'width' => $this->width,
            'height' => $this->height,
            'volume' => $this->volume,
            'stock_item' => (bool) $this->stock_item,
            'current_stock' => $this->current_stock,
            'reorder_level' => $this->reorder_level,
            'reorder_quantity' => $this->reorder_quantity,
            'minimum_stock_level' => $this->minimum_stock_level,
            'maximum_stock_level' => $this->maximum_stock_level,
            'safety_stock' => $this->safety_stock,
            'storage_location' => $this->storage_location,
            'warehouse' => $this->warehouse,
            'bin_location' => $this->bin_location,
            'preferred_supplier_id' => $this->preferred_supplier_id ? (string) $this->preferred_supplier_id : null,
            'preferred_supplier_name' => $this->preferredSupplier?->name,
            'supplier_material_code' => $this->supplier_material_code,
            'lead_time_days' => $this->lead_time_days,
            'minimum_order_quantity' => $this->minimum_order_quantity,
            'purchase_rate' => $this->purchase_rate,
            'last_purchase_rate' => $this->last_purchase_rate,
            'standard_cost' => $this->standard_cost,
            'currency' => $this->currency,
            'material_cost' => $this->material_cost,
            'transportation_cost' => $this->transportation_cost,
            'loading_unloading_cost' => $this->loading_unloading_cost,
            'tax_percentage' => $this->tax_percentage,
            'landed_cost' => $this->landed_cost,
            'budget_cost' => $this->budget_cost,
            'project_allocation' => $this->project_allocation,
            'wbs_code' => $this->wbs_code,
            'cost_center' => $this->cost_center,
            'material_usage_type' => $this->material_usage_type,
            'project_consumption_tracking' => (bool) $this->project_consumption_tracking,
            'material_issue_method' => $this->material_issue_method,
            'gst_rate' => $this->gst_rate,
            'hsn_sac_code' => $this->hsn_sac_code,
            'tax_category' => $this->tax_category,
            'compliance_certificate_reference' => $this->compliance_certificate_reference,
            'quality_inspection_required' => (bool) $this->quality_inspection_required,
            'inspection_frequency' => $this->inspection_frequency,
            'quality_standards' => $this->quality_standards,
            'acceptance_criteria' => $this->acceptance_criteria,
            'test_certificate_required' => (bool) $this->test_certificate_required,
            'grade' => $this->grade,
            'color' => $this->color,
            'size' => $this->size,
            'thickness' => $this->thickness,
            'density' => $this->density,
            'strength_rating' => $this->strength_rating,
            'technical_specifications' => $this->technical_specifications,
            'batch_number' => $this->batch_number,
            'lot_number' => $this->lot_number,
            'serial_number' => $this->serial_number,
            'manufacturing_date' => optional($this->manufacturing_date)->toDateString(),
            'expiry_date' => optional($this->expiry_date)->toDateString(),
            'warranty_period' => $this->warranty_period,
            'material_datasheets' => $this->material_datasheets,
            'product_catalogs' => $this->product_catalogs,
            'test_certificates' => $this->test_certificates,
            'quality_reports' => $this->quality_reports,
            'material_images' => $this->material_images,
            'safety_data_sheets' => $this->safety_data_sheets,
            'archived_at' => $this->archived_at,
        ];
    }
}
